### ISSUE TITLE
VSCode hangs on installing extensions for dev containers (M1/2 CPUs)

### ISSUE THREAD

**Issue by 1995parham** [1995parham/dotfiles#57]
It has been a while since VSCode started hanging while installing extensions for dev containers. I think it began after the latest macOS release. I found issue microsoft/vscode-remote-release#8169, which seems to point to the same issue I’m experiencing. The issue is about the verification process consuming all the CPU without making any progress. For now, the easiest solution is to disable it as follows:

```jsonc
// Bug fix on Mac: https://github.com/microsoft/vscode-remote-release/issues/8169
"settings": {
  "extensions.verifySignature": false
},
// Add the IDs of extensions you want installed when the container is created.
"extensions": [
  "ms-python.python"
]
```

**Comment by cidrbl0ck** [comment]
Commenting here because I encountered this exact problem today, I'm running VScode 1.89 on an M3 Pro, 36gb, Sonoma 14.4.1 MBP.
What's different about my issue is everything works fine if I use a public image say ghcr.io/ansible/creator-ee. But any custom image.. even a copy of the creator-ee one stored internally with no changes.. all the extensions install forever.  Doing the Developer Reload Window is the first thing that I tried that worked.
